services:
  mongodb:
    image: mongo:8
    container_name: codejudge-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: codejudge
      MONGO_INITDB_ROOT_PASSWORD: codejudge
      MONGO_INITDB_DATABASE: codejudge
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
